#
# from bs4 import BeautifulSoup
#
# # import lxml is target web is  xml
#
# file = open('website.html', encoding="utf8")
# contents = file.read()
#
# soup = BeautifulSoup(contents, 'html.parser')
#
# all_tags = soup.find_all('p')  # returns list
# tag = soup.find(name='h1', id='name')  # returns list
# print(tag)
#
# heading = soup.select_one(selector='.heading_1')
# print(heading)
#
{
  'tracks': {
    'href': 'https://api.spotify.com/v1/search?query=track%3ASave+The+Best+For+Last+year%3A1992&type=track&offset=0&limit=10',
    'items': [
      {
        'album': {
          'album_type': 'compilation',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of'
              },
              'href': 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
              'id': '0LyfQWJT6nXafLPZqxe9Of',
              'name': 'Various Artists',
              'type': 'artist',
              'uri': 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/1TEEUGOzZueB4jrgJ7JQd4'
          },
          'href': 'https://api.spotify.com/v1/albums/1TEEUGOzZueB4jrgJ7JQd4',
          'id': '1TEEUGOzZueB4jrgJ7JQd4',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/ab67616d0000b273883c4871a373fae240f407fc',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/ab67616d00001e02883c4871a373fae240f407fc',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/ab67616d00004851883c4871a373fae240f407fc',
              'width': 64
            }
          ],
          'name': 'Reggae Hits, Vol.13',
          'release_date': '1992-02-07',
          'release_date_precision': 'day',
          'total_tracks': 18,
          'type': 'album',
          'uri': 'spotify:album:1TEEUGOzZueB4jrgJ7JQd4'
        },
        'artists': [
          {
            'external_urls': {
              'spotify': 'https://open.spotify.com/artist/1ABKdHci1opQWv1GLXH0Na'
            },
            'href': 'https://api.spotify.com/v1/artists/1ABKdHci1opQWv1GLXH0Na',
            'id': '1ABKdHci1opQWv1GLXH0Na',
            'name': 'Singing Sweet',
            'type': 'artist',
            'uri': 'spotify:artist:1ABKdHci1opQWv1GLXH0Na'
          }
        ],
        'available_markets': [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW'
        ],
        'disc_number': 1,
        'duration_ms': 222600,
        'explicit': False,
        'external_ids': {
          'isrc': 'GBVVQ1022877'
        },
        'external_urls': {
          'spotify': 'https://open.spotify.com/track/41QUPxR6wWk5Ty1lz6YkNu'
        },
        'href': 'https://api.spotify.com/v1/tracks/41QUPxR6wWk5Ty1lz6YkNu',
        'id': '41QUPxR6wWk5Ty1lz6YkNu',
        'is_local': False,
        'name': 'Save the Best for Last',
        'popularity': 3,
        'preview_url': 'https://p.scdn.co/mp3-preview/be2913821e04d17baaa9a96f709db880a5e26300?cid=48984c01bd0540a9ad9ca60d0c178814',
        'track_number': 18,
        'type': 'track',
        'uri': 'spotify:track:41QUPxR6wWk5Ty1lz6YkNu'
      },
      {
        'album': {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/1VL76sio3k58IeQUiotQhv'
              },
              'href': 'https://api.spotify.com/v1/artists/1VL76sio3k58IeQUiotQhv',
              'id': '1VL76sio3k58IeQUiotQhv',
              'name': 'Moonjam',
              'type': 'artist',
              'uri': 'spotify:artist:1VL76sio3k58IeQUiotQhv'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AZ',
            'BA',
            'BB',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BO',
            'BR',
            'BS',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HN',
            'HR',
            'HT',
            'HU',
            'IE',
            'IL',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KM',
            'KN',
            'KW',
            'KZ',
            'LB',
            'LC',
            'LI',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MK',
            'ML',
            'MN',
            'MR',
            'MT',
            'MU',
            'MW',
            'MX',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'OM',
            'PA',
            'PE',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SC',
            'SE',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TJ',
            'TN',
            'TR',
            'TT',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'XK',
            'ZA',
            'ZM',
            'ZW'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/7sfyEf5fmFFe1CnZ9xf38P'
          },
          'href': 'https://api.spotify.com/v1/albums/7sfyEf5fmFFe1CnZ9xf38P',
          'id': '7sfyEf5fmFFe1CnZ9xf38P',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/ab67616d0000b27396fc50ee831d6f23b8366721',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/ab67616d00001e0296fc50ee831d6f23b8366721',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/ab67616d0000485196fc50ee831d6f23b8366721',
              'width': 64
            }
          ],
          'name': 'Songs For Saxophone',
          'release_date': '1992-09-27',
          'release_date_precision': 'day',
          'total_tracks': 11,
          'type': 'album',
          'uri': 'spotify:album:7sfyEf5fmFFe1CnZ9xf38P'
        },
        'artists': [
          {
            'external_urls': {
              'spotify': 'https://open.spotify.com/artist/1VL76sio3k58IeQUiotQhv'
            },
            'href': 'https://api.spotify.com/v1/artists/1VL76sio3k58IeQUiotQhv',
            'id': '1VL76sio3k58IeQUiotQhv',
            'name': 'Moonjam',
            'type': 'artist',
            'uri': 'spotify:artist:1VL76sio3k58IeQUiotQhv'
          }
        ],
        'available_markets': [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AZ',
          'BA',
          'BB',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BO',
          'BR',
          'BS',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HN',
          'HR',
          'HT',
          'HU',
          'IE',
          'IL',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KM',
          'KN',
          'KW',
          'KZ',
          'LB',
          'LC',
          'LI',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MK',
          'ML',
          'MN',
          'MR',
          'MT',
          'MU',
          'MW',
          'MX',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'OM',
          'PA',
          'PE',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SC',
          'SE',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TJ',
          'TN',
          'TR',
          'TT',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'XK',
          'ZA',
          'ZM',
          'ZW'
        ],
        'disc_number': 1,
        'duration_ms': 190373,
        'explicit': False,
        'external_ids': {
          'isrc': 'DKADG9202805'
        },
        'external_urls': {
          'spotify': 'https://open.spotify.com/track/5uVn0vsg8XPpDouamhD95Z'
        },
        'href': 'https://api.spotify.com/v1/tracks/5uVn0vsg8XPpDouamhD95Z',
        'id': '5uVn0vsg8XPpDouamhD95Z',
        'is_local': False,
        'name': 'Save The Best For Last',
        'popularity': 11,
        'preview_url': 'https://p.scdn.co/mp3-preview/9398d5baf28bb7725da8233a3d55f3cbf5dd985d?cid=48984c01bd0540a9ad9ca60d0c178814',
        'track_number': 5,
        'type': 'track',
        'uri': 'spotify:track:5uVn0vsg8XPpDouamhD95Z'
      },
      {
        'album': {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/1BQ9V1udaPu0MEPXkcmIvX'
              },
              'href': 'https://api.spotify.com/v1/artists/1BQ9V1udaPu0MEPXkcmIvX',
              'id': '1BQ9V1udaPu0MEPXkcmIvX',
              'name': 'Tiffany Phương Thúy',
              'type': 'artist',
              'uri': 'spotify:artist:1BQ9V1udaPu0MEPXkcmIvX'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/6ctbVKVWBOu7JxVCOf6rEh'
          },
          'href': 'https://api.spotify.com/v1/albums/6ctbVKVWBOu7JxVCOf6rEh',
          'id': '6ctbVKVWBOu7JxVCOf6rEh',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/ab67616d0000b27320715db5401fbad94c556c6f',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/ab67616d00001e0220715db5401fbad94c556c6f',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/ab67616d0000485120715db5401fbad94c556c6f',
              'width': 64
            }
          ],
          'name': 'For get me not - Tiffany Phương Thúy',
          'release_date': '1992-01-01',
          'release_date_precision': 'day',
          'total_tracks': 12,
          'type': 'album',
          'uri': 'spotify:album:6ctbVKVWBOu7JxVCOf6rEh'
        },
        'artists': [
          {
            'external_urls': {
              'spotify': 'https://open.spotify.com/artist/1BQ9V1udaPu0MEPXkcmIvX'
            },
            'href': 'https://api.spotify.com/v1/artists/1BQ9V1udaPu0MEPXkcmIvX',
            'id': '1BQ9V1udaPu0MEPXkcmIvX',
            'name': 'Tiffany Phương Thúy',
            'type': 'artist',
            'uri': 'spotify:artist:1BQ9V1udaPu0MEPXkcmIvX'
          }
        ],
        'available_markets': [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW'
        ],
        'disc_number': 1,
        'duration_ms': 221186,
        'explicit': False,
        'external_ids': {
          'isrc': 'VNA0F1700977'
        },
        'external_urls': {
          'spotify': 'https://open.spotify.com/track/1os1qbIrpLJa262zBLU1LZ'
        },
        'href': 'https://api.spotify.com/v1/tracks/1os1qbIrpLJa262zBLU1LZ',
        'id': '1os1qbIrpLJa262zBLU1LZ',
        'is_local': False,
        'name': 'Save the best for last',
        'popularity': 0,
        'preview_url': 'https://p.scdn.co/mp3-preview/f0832ce7557881d0ddcf26ec38c93b13a9f25273?cid=48984c01bd0540a9ad9ca60d0c178814',
        'track_number': 12,
        'type': 'track',
        'uri': 'spotify:track:1os1qbIrpLJa262zBLU1LZ'
        sd
      }
    ],
    'limit': 10,
    'next': None,
    'offset': 0,
    'previous': None,
    'total': 3
  }
}